version: '3.8'

services:
  basket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basket-api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__SqlServer: "Server=db;Database=Basket;User Id=sa;Password=Your_password123;TrustServerCertificate=True"

      ConnectionStrings__Redis: "redis:6379"

      RabbitMq__Host: "rabbitmq"
      RabbitMq__Username: "guest"
      RabbitMq__Password: "guest"

    depends_on:
      - db
      - redis
      - rabbitmq

    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: basket-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: basket-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: basket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  mssql-data: